env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - SCHEME="MessagePacker"

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild test -scheme "$SCHEME" -destination "name=iPhone X" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild test -scheme "$SCHEME" -destination "arch=x86_64" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild test -scheme "$SCHEME" -destination "name=Apple TV 4K" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild build -scheme "$SCHEME" -destination "OS=8.4,name=iPhone 5" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild build -scheme "$SCHEME" -destination "name=Apple Watch Series 2 - 42mm" -configuration Release ENABLE_TESTABILITY=YES | xcpretty

    - os: osx
      language: objective-c
      osx_image: xcode10.1
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild test -scheme "$SCHEME" -destination "name=iPhone X" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild test -scheme "$SCHEME" -destination "arch=x86_64" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild test -scheme "$SCHEME" -destination "name=Apple TV 4K" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild build -scheme "$SCHEME" -destination "OS=8.4,name=iPhone 5" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        - xcodebuild build -scheme "$SCHEME" -destination "name=Apple Watch Series 2 - 42mm" -configuration Release ENABLE_TESTABILITY=YES | xcpretty

    - os: osx
      language: generic
      osx_image: xcode9.4
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test

    - os: osx
      language: generic
      osx_image: xcode10.1
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION=4.1
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION=4.2
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift build
        - swift test

deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
