env:
  global:
  - SCHEME="MessagePacker"

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.4
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild test -scheme "$SCHEME" -destination "name=iPhone X" -configuration Debug | xcpretty
        - xcodebuild build -scheme "$SCHEME" -destination "OS=8.4,name=iPhone 5" -configuration Debug | xcpretty
        - xcodebuild test -scheme "$SCHEME" -destination "arch=x86_64" -configuration Debug | xcpretty
    - language: objective-c
      os: osx
      osx_image: xcode10.1
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild test -scheme "$SCHEME" -destination "name=iPhone X" -configuration Debug | xcpretty
        - xcodebuild test -scheme "$SCHEME" -destination "OS=8.4,name=iPhone 5" -configuration Debug | xcpretty
        - xcodebuild test -scheme "$SCHEME" -destination "arch=x86_64" -configuration Debug | xcpretty
